language: go

before_install:
  - make redis-server/redis-server

cache:
  directories:
    - $HOME/redis-server

install:
  - go get -t -v ./...


jobs:
  include:
    - go: "1.9.x"
      script: make testredis
    - go: "1.9.x"
      script: make testconn
    - go: "1.9.x"
      script: make testcluster
    - go: "1.12.x"  
      script: make testredis
    - go: "1.12.x"
      script: make testconn
    - go: "1.12.x"
      script: make testcluster
