language: go

go:
  - "1.9.x"
  - "1.12.x"

env:
  matrix:
    - STAGE=testredis
    - STAGE=testconn
    - STAGE=testcluster

addons:
  apt:
    packages:
      - realpath

before_install:
  - make /tmp/redis-server/redis-server

cache:
  directories:
    - /tmp/redis-server

install:
  - go get -t -v ./...

script: make $STAGE
